from typing import Any, Callable, Dict, List, Optional
from libevent.handler import Handler
from libevent.event import Event


def init(app_id: str = None, handlers: List[Handler] = None) -> None: ...
def add_field(name: str, val: Any) -> None: ...
def add(data: Dict) -> None: ...
def new_event(data: Optional[Dict] = None,
              calling_func: Callable = None,
              parent_id: str = None,
              event_id: str = None) -> Event: ...
