from typing import Any, Dict, List, Optional
from libevent.handler import Handler


class Client:
    def __init__(self, handlers: Optional[List[Handler]] = None) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def add_field(self, name: str, value: Any) -> None: ...
    def add(self, data: Dict) -> None: ...
    def send(self, evt: Any) -> None: ...
